In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("/content/Advertising.csv")

In [3]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [4]:
x = df[["TV", "Radio", "Newspaper"]].values

In [5]:
x

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [6]:
y = df['Sales'].values

In [7]:
y

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2, 11.8, 13.2,  4.8, 15.6, 12.6,
       17.4,  9.2, 13.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 17.5,
        5.6, 20.5,  9.7, 17. , 15. , 20.9, 18.9, 10.5, 21.4, 11.9, 13.2,
       17.4, 11.9, 17.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 17.9,
        8.5, 16.1, 10.6, 23.2, 19.8,  9.7, 16.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 20.7, 14. , 16. , 11.3,
       11. , 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 17.3, 11.3, 13.6, 21.7, 20.2, 12. , 16. ,
       12.9, 16.7, 14. ,  7.3, 19.4, 22.2, 11.5, 16.9, 16.7, 20.5, 25.4,
       17.2, 16.7, 23.8, 19.8, 19.7, 20.7, 15. ,  7.2, 12. ,  5.3, 19.8,
       18.4, 21.8, 17.1, 20.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 16.6, 15.2, 19.7, 10.6,  6.6, 11.9, 24.7,  9.7,  1.6, 17.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 12.3, 10.3, 18.2, 25.4, 10.9, 10.1, 16

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
Lin = LinearRegression()

In [10]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
pred_y = Lin.predict(x)

In [12]:
y - pred_y

array([ 0.87902791, -0.86824775,  1.50379103, -0.81244651,  2.25586315,
       -3.15633677,  0.5267153 , -0.07062458, -0.51839603, -0.18871013,
        3.7472798 , -1.48400523, -0.49879662,  2.95078627, -0.27328852,
        2.01445555,  0.22894206,  0.19785498,  0.7075602 , -0.60872794,
       -1.49794066, -0.60414656, -1.46177654,  1.62778928,  0.32854579,
       -2.31996936, -0.54479137,  1.40783698, -2.17865408,  0.30528933,
       -2.21492832, -0.74683045,  3.11217449, -3.8260486 ,  1.91212915,
       -3.09407055,  1.55496506,  0.70657589,  0.2595484 ,  0.41655065,
       -1.44712878, -0.74885818, -2.87494339,  1.10237228, -0.25617872,
       -0.47668108,  0.01979428,  1.06657257,  1.09742589,  0.16818663,
        0.55329144, -0.41990058,  1.71756578,  1.66991657, -1.81500291,
        2.93961006, -2.54320903, -0.90063486,  2.3777902 , -0.85650785,
        0.34084114,  0.76088058,  1.37831819,  0.6132384 , -0.35231896,
        1.92270356,  2.02686518, -0.3643628 , -1.59677834,  1.16

In [13]:
np.abs(y - pred_y).mean()

1.2363919943957848

In [14]:
from sklearn import metrics

In [15]:
metrics.mean_absolute_error(y, pred_y)

1.2363919943957848

In [16]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [17]:
x = df[["TV"]].values

In [18]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
pred_yTV = Lin.predict(x)

In [20]:
metrics.mean_absolute_error(y, pred_yTV)

1.8305872641932412

In [21]:
x = df[["TV", "Radio"]].values

In [22]:
Lin.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
pred_yTVR = Lin.predict(x)

In [24]:
metrics.mean_absolute_error(y, pred_yTVR)

1.2367636706717362